name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - colcon-common-extensions
  - vcstool
  - rosdep
  - eigen=3
  - boost=1.69
  - opencv=3
  - tinyxml2
  - sip=4.19.20
  - qt
  - poco
  - console_bridge
  - bzip2
  - python-orocos-kdl
